---
title: "Estimation of subnational fertility in SSA"
author: "Oli Stevens"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
  keep_md: true
# vignette: >
#   %\VignetteIndexEntry{Model-based smoothing of child mortality trends}
# %\VignetteEngine{knitr::rmarkdown}
# %\VignetteEncoding{UTF-8}
---
  
  ```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  cache = TRUE,
  comment = "#>"
)
```

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 600)
```

## Load packages

```{r load packages, results=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(rdhs)
library(demogsurv)
library(INLA)
library(reshape2)
```


## Calculate ASFR, TFR
``` {r calculate ASFRs, warning=FALSE}
surveys <- dhs_surveys(countryIds = "MW", surveyYearStart=1995)
ird <- dhs_datasets(fileType = "IR", fileFormat = "flat", surveyIds = surveys$SurveyId)
ird$path <- unlist(get_datasets(ird))


ir <- lapply(ird$path, readRDS) %>%
  Map(data.frame,
      surveyid = surveys$SurveyId,
      country = surveys$CountryName,
      survyear = surveys$SurveyYear,
      survtype = surveys$SurveyType,
      .,
      stringsAsFactors = FALSE)

tips_surv <- list("DHS" = c(0, 7), "MIS" = c(0, 5))[surveys$SurveyType]

tfr <- Map(calc_tfr, ir,
           by = list(~surveyid + country + survyear + v025),
           tips = tips_surv,
           period = list(1995:2017))

tfr <- tfr %>%
  bind_rows %>%
  type.convert %>% 
  mutate(v025 = factor(v025, levels= c(1,2), labels = c("Urban", "Rural"))) %>%
  filter(period <= survyear) %>%
  mutate(lower = tfr - qnorm(0.975) * se_tfr,
         upper = tfr + qnorm(0.975) * se_tfr)

asfr <- Map(calc_asfr, ir,
            by = list(~surveyid + country + survyear+ v025),
            tips = tips_surv,
            period = list(1995:2017),
            counts = TRUE)
```
## Create id indicies for age, period, and age.period.
``` {r manip, warning=FALSE}
asfr1 <- asfr %>%
  bind_rows %>%
  type.convert %>%
  mutate(v025 = factor(v025, levels= c(1,2), labels = c("Urban", "Rural"))) %>%
  filter(period <= survyear) %>%
  mutate(id.period = group_indices(., period),
         id.period2 = id.period,
         id.agegr = group_indices(., agegr),
         id.agegr2 = id.agegr,
         id.agegr.period = group_indices(., period, agegr),
         id = 1:nrow(.))
```
## Append prediction dataframe (NA for outcome, pys=1)
``` {r warning=FALSE}
asfr_pred <- asfr %>%
  bind_rows %>%
  type.convert %>%
  mutate(v025 = factor(v025, levels= c(1,2), labels = c("Urban", "Rural"))) %>%
  filter(period <= survyear) %>%
  mutate(births = NA_integer_,
         pys = 1,
         asfr = NA_integer_,
         se_asfr = NA_integer_)%>%
  select("v025", "agegr", "period", "pys") %>%
  group_by_all() %>%
  summarise() %>%
  ungroup() %>%
  bind_rows(asfr %>%
              bind_rows %>%
              type.convert %>%
              mutate(v025 = factor(v025, levels= c(1,2), labels = c("Urban", "Rural"))) %>%
              filter(period <= survyear)) %>%
  mutate(id.period = group_indices(., period),
         id.period2 = id.period,
         id.agegr = group_indices(., agegr),
         id.agegr2 = id.agegr,
         id.agegr.period = group_indices(., period, agegr),
         id = 1:nrow(.))
```
# Models

## Age as iid

``` {r mod1}
formula.1 <- births ~ v025 + period + f(id.agegr, model="iid")

mod <- inla(formula.1, family="poisson", data=asfr_pred, offset=log(pys),
            control.family=list(link='log'),
            control.predictor=list(compute=TRUE, link=1),
            control.compute=list(config = TRUE, dic= TRUE, cpo=TRUE))
summary(mod)
```

Posterior distribution from age group random effect
``` {r echo=FALSE, fig.width=7, fig.height=4, warning=FALSE}

lapply(mod$marginals.random$id.agegr, exp) %>%
       melt() %>%
       pivot_wider(names_from=Var2) %>%
       mutate(L1 = factor(as.numeric(factor(L1)), labels=unique(asfr1$agegr))) %>%
  ggplot(aes(x=x, y=y, group=L1)) +
  geom_line(aes(color=L1)) +
  xlim(0,3)

exp(mod$summary.random$id.agegr) %>%
  rename(lower = "0.025quant", upper = "0.975quant") %>%
  mutate(agegr = unique(asfr1$agegr)) %>%
  ggplot(aes(x=agegr, y=mean)) +
    geom_point()+
    geom_errorbar(aes(ymin=lower, ymax=upper, width=0.5))
```

## Make age a 2nd order RW

``` {r mod2}
formula.2 <- births ~ v025 + period + f(id.agegr, model="rw2")
```

Posterior distribution from age group random effect

``` {r echo=FALSE, fig.width=7, fig.height=5}
mod <- inla(formula.2, family="poisson", data=asfr_pred, offset=log(pys),
            control.family=list(link='log'),
            control.predictor=list(compute=TRUE, link=1),
            control.compute=list(config = TRUE, dic= TRUE, cpo=TRUE))

summary(mod)

lapply(mod$marginals.random$id.agegr, exp) %>%
       melt() %>%
       pivot_wider(names_from=Var2) %>%
       mutate(L1 = factor(as.numeric(factor(L1)), labels=unique(asfr1$agegr))) %>%
  ggplot(aes(x=x, y=y, group=L1)) +
  geom_line() +
  xlim(0,3) +
  facet_wrap(~L1, scales="free")

exp(mod$summary.random$id.agegr) %>%
  rename(lower = "0.025quant", upper = "0.975quant") %>%
  mutate(agegr = unique(asfr1$agegr)) %>%
  ggplot(aes(x=agegr, y=mean)) +
    geom_point()+
    geom_errorbar(aes(ymin=lower, ymax=upper, width=0.5))
```

## Include RW2 over period

``` {r mod3}
formula.3 <- births ~ v025 + f(id.period, model="rw2") + f(id.agegr, model="rw2")
```

Posterior distribution from age group random effect

``` {r echo=FALSE, fig.width=7, fig.height=5}
mod <- inla(formula.3, family="poisson", data=asfr_pred, offset=log(pys),
            control.family=list(link='log'),
            control.predictor=list(compute=TRUE, link=1),
            control.compute=list(config = TRUE, dic= TRUE, cpo=TRUE))

summary(mod)

lapply(mod$marginals.random$id.agegr, exp) %>%
       melt() %>%
       pivot_wider(names_from=Var2) %>%
       mutate(L1 = factor(as.numeric(factor(L1)), labels=unique(asfr1$agegr))) %>%
  ggplot(aes(x=x, y=y, group=L1)) +
  geom_line() +
  xlim(0,3) +
  facet_wrap(~L1, scales="free")

exp(mod$summary.random$id.agegr) %>%
  rename(lower = "0.025quant", upper = "0.975quant") %>%
  mutate(agegr = unique(asfr1$agegr)) %>%
  ggplot(aes(x=agegr, y=mean)) +
    geom_point()+
    geom_errorbar(aes(ymin=lower, ymax=upper, width=0.5))
```