---
title: "ETH spatial comparison | 2020_05_20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, results="hide", echo=FALSE}
library(TMB)
library(INLA)
library(tidyverse)
library(abind)
library(sf)
library(spdep)
library(Matrix)
library(countrycode)
library(haven)
library(survival)
library(parallel)
library(demogsurv)
devtools::load_all("~/Documents/GitHub/naomi")
# library(naomi)
library(here)

naomi_data_path <- "~/Imperial College London/HIV Inference Group - Documents/Analytical datasets/naomi-data"
# naomi_data_path <- "~/naomi-data"

mics_key <- read.csv(here("countries/mics_data_key.csv"))

source(here("R/inputs.R"))
source(here("R/fertility_funs.R"))

iso3_current <-  "ETH"
list2env(make_areas_population(iso3_current, naomi_data_path, full = FALSE), globalenv())

exclude_districts=""

asfr <- get_asfr_pred_df(iso3_current, area_level = "naomi", areas_long, project = FALSE)

if(filter(mics_key, iso3 == iso3_current)$mics) {
  mics_asfr <- readRDS(here(grep("mics", list.files(paste0("countries/", iso3_current, "/data"), full.names = TRUE), value=TRUE)))
} else {
  mics_asfr <- NULL
}

mf <- make_model_frames(iso3_current, population, asfr, mics_asfr, exclude_districts, project=FALSE)

Z_spatial <- sparse.model.matrix(~0 + area_id, mf$mf_model)
Z_age <- sparse.model.matrix(~0 + age_group, mf$mf_model)
Z_period <- sparse.model.matrix(~0 + period, mf$mf_model)

M_obs <- sparse.model.matrix(~0 + idx, mf$dist$obs) 
Z_tips <- sparse.model.matrix(~0 + tips_f, mf$dist$obs)
X_tips_dummy <- model.matrix(~0 + tips_dummy, mf$dist$obs)

if(mf$mics_toggle) {
  M_obs_mics <- sparse.model.matrix(~0 + idx, mf$mics$obs) 
  Z_tips_mics <- sparse.model.matrix(~0 + tips_f, mf$mics$obs)
  X_tips_dummy_mics <- model.matrix(~0 + tips_dummy, mf$mics$obs)
}

R_spatial <- make_adjacency_matrix(iso3_current, areas_long, boundaries, exclude_districts, level= "naomi")
R_tips <- make_rw_structure_matrix(ncol(Z_tips), 1, TRUE)
R_age <- make_rw_structure_matrix(ncol(Z_age), 1, TRUE)
R_period <- make_rw_structure_matrix(ncol(Z_period), 2, TRUE)

# dyn.unload(dynlib(here("tmb/fertility_tmb_dev")))
compile(here("tmb/fertility_tmb_dev.cpp"))               # Compile the C++ file
dyn.load(dynlib(here("tmb/fertility_tmb_dev")))

ar1_phi_age <- 0.99
ar1_phi_period <- 0.99

data <- list(M_obs = M_obs,
             X_tips_dummy = X_tips_dummy,
             # X_urban_dummy = X_urban_dummy,
             Z_tips = Z_tips,
             Z_age = Z_age,
             Z_period = Z_period,
             Z_spatial = Z_spatial,
             Z_interaction1 = sparse.model.matrix(~0 + id.interaction1, mf$mf_model),
             Z_interaction2 = sparse.model.matrix(~0 + id.interaction2, mf$mf_model),
             Z_interaction3 = sparse.model.matrix(~0 + id.interaction3, mf$mf_model),
             R_tips = R_tips,
             R_age = R_age,
             R_period = R_period,
             R_spatial = R_spatial,
             ar1_phi_age = ar1_phi_age,
             ar1_phi_period = ar1_phi_period,
             log_offset = log(mf$dist$obs$pys),
             births_obs = mf$dist$obs$births,
             pop = mf$mf_model$population,
             A_out = mf$out$A_out,
             # A_out_restype = mf$out$A_out_restype,
             mics_toggle = mf$mics_toggle,
             out_toggle = mf$out_toggle
)

par <- list(
  beta_0 = 0,
  beta_tips_dummy = rep(0, ncol(X_tips_dummy)),
  # beta_urban_dummy = rep(0, ncol(X_urban_dummy)),
  u_tips = rep(0, ncol(Z_tips)),
  u_age = rep(0, ncol(Z_age)),
  u_period = rep(0, ncol(Z_period)),
  u_spatial_str = rep(0, ncol(Z_spatial)),
  u_spatial_iid = rep(0, ncol(Z_spatial)),
  eta1 = array(0, c(ncol(Z_period), ncol(Z_age))),
  log_sigma_eta1 = log(2.5),
  eta2 = array(0, c(ncol(Z_spatial), ncol(Z_period))),
  log_sigma_eta2 = log(2.5),
  eta3 = array(0, c(ncol(Z_spatial), ncol(Z_age))),
  log_sigma_eta3 = log(2.5),
  log_sigma_rw_period = log(2.5),
  log_sigma_rw_age = log(2.5),
  log_sigma_rw_tips = log(2.5),
  log_sigma_spatial = log(2.5),
  logit_spatial_rho = 0
)

random <- c("beta_0", "beta_tips_dummy","u_tips", "u_age", "u_period", "u_spatial_str", "u_spatial_iid", "eta1", "eta2", "eta3")

if(mf$mics_toggle) {
  data <- c(data, "M_obs_mics" = M_obs_mics,
            "X_tips_dummy_mics" = list(X_tips_dummy_mics),
            "Z_tips_mics" = Z_tips_mics,
            "births_obs_mics" = list(mf$mics$obs$births),
            "log_offset_mics" = list(log(mf$mics$obs$pys)),
            "A_mics" = mf$mics$A_mics)
  par <- c(par, "beta_tips_dummy_mics" = rep(0, ncol(X_tips_dummy_mics)))
  random = c(random, "beta_tips_dummy_mics")
}


f <- mcparallel({TMB::MakeADFun(data = data,
                                parameters = par,
                                DLL = "fertility_tmb_dev",
                                silent=0,
                                checkParameterOrder=FALSE)
})

# mccollect(f)

obj <-  MakeADFun(data = data,
                  parameters = par,
                  DLL = "fertility_tmb_dev",
                  #  random = c("beta_mf", "beta_tips_dummy", "u_tips", "u_age", "u_period", "u_spatial_str", "u_spatial_iid", "eta1", "eta2", "eta3"),
                  random = random,
                  hessian = FALSE)

f <- nlminb(obj$par, obj$fn, obj$gr)
f$par.fixed <- f$par
f$par.full <- obj$env$last.par

fit <- c(f, obj = list(obj))
fit$sdreport <- sdreport(fit$obj, fit$par)

class(fit) <- "naomi_fit"  # this is hacky...
```

## Here sample with both arguments to random_only

``` {r message=FALSE, warning=FALSE, results="hide"}
fit_rndm <- sample_tmb(fit)
fit_all <- sample_tmb(fit, random_only = FALSE)

qtls_rndm <- apply(fit_rndm$sample$lambda_out, 1, quantile, c(0.025, 0.5, 0.975))
qtls_all <- apply(fit_all$sample$lambda_out, 1, quantile, c(0.025, 0.5, 0.975))

```

## 10 districts with the highest uncertainty in both TMB and INLA are the same, but TMB much more uncertain.

``` {r message=FALSE, warning=FALSE, echo=FALSE}

eth.m <- readRDS(here("countries/ETH/mods/ETH_INLA_full.rds"))
asfr <- get_asfr_pred_df("ETH", area_level = "naomi", areas_long, project = FALSE)
asfr <- make_asfr_pred_df(asfr, t2 = 2016)
eth_res <- get_mod_results_test(eth.m, asfr)

p <- mf$out$mf_out %>%
    mutate(lower = qtls_rndm[1,],
           median = qtls_rndm[2,],
           upper = qtls_rndm[3,],
           source = "tmb") %>%
    type.convert() %>%
    left_join(areas_long) %>%
    filter(area_level == 2) %>%
    bind_rows(eth_res %>% mutate(source = "INLA") %>% left_join(areas_long))

top10 <- p %>%
  mutate(diff = upper-lower) %>%
  filter(period == 2015, age_group == "25-29") %>%
  group_split(source) %>%
  lapply(function(x) {
    x %>%
      arrange(desc(diff)) %>%
      mutate(idx = row_number()) %>%
      filter(idx < 11)
  }) %>%
  bind_rows %>%
  .$area_id %>%
  unique

p %>%
  filter(area_id %in% top10, age_group == "25-29") %>%
  type.convert() %>%
  ggplot(aes(x=period, y=median, group=source)) +
  geom_line(aes(color=source)) +
  geom_ribbon(aes(ymin=lower, ymax=upper, fill=source), alpha = 0.3) +
  facet_wrap(~area_name) +
  labs(title="ASFR for 25-29")

```

```{r message=FALSE, warning=FALSE}

tmb_rho <- data.frame("x" = fit_all$sample$logit_spatial_rho)
inla_rho <- data.frame(eth.m$internal.marginals.hyperpar$`Logit phi for id.district`)

inla_rho %>%
  ggplot() +
    geom_point(aes(x=x, y=y)) +
    geom_density(data = tmb_rho, aes(x=x)) +
    labs(title="Logit Rho. INLA = points, TMB = line")
```

## Note here log precision from TMB is -2*log sigma as you previously transformed to match the INLA precisions.

``` {r message=FALSE, warning=FALSE}
tmb_log_spatial_prec <- data.frame("x" = fit_all$sample$log_tau2_spatial)
inla_spatial_precision <- data.frame(eth.m$internal.marginals.hyperpar$`Log precision for id.district`)

inla_spatial_precision %>%
  ggplot() +
  geom_point(aes(x=x, y=y)) +
  geom_density(data = tmb_log_spatial_prec, aes(x=x)) +
  xlim(0, 10) +
  labs(title="Log prec sigma. INLA = points, TMB = line")

```


## Results using random_only = TRUE

``` {r message=FALSE, warning=FALSE, echo=FALSE}

mf$out$mf_out %>%
    mutate(lower = qtls_rndm[1,],
           median = qtls_rndm[2,],
           upper = qtls_rndm[3,],
           source = "tmb") %>%
    type.convert() %>%
    left_join(areas_long) %>%
    filter(area_level == 2,) %>%
    bind_rows(eth_res %>% mutate(source = "INLA") %>% left_join(areas_long)) %>%
    filter(area_id %in% top10, age_group == "25-29") %>%
    ggplot(aes(x=period, y=median, group=source)) +
      geom_line(aes(color=source)) +
      geom_ribbon(aes(ymin=lower, ymax=upper, fill=source), alpha = 0.3) +
      facet_wrap(~area_name)
    

```

## Results using random_only = FALSE

``` {r message=FALSE, warning=FALSE, echo=FALSE}

mf$out$mf_out %>%
    mutate(lower = qtls_all[1,],
           median = qtls_all[2,],
           upper = qtls_all[3,],
           source = "tmb") %>%
    type.convert() %>%
    left_join(areas_long) %>%
    filter(area_level == 2) %>%
    bind_rows(eth_res %>% mutate(source = "INLA") %>% left_join(areas_long)) %>%
    filter(area_id %in% top10, age_group == "25-29") %>%
    ggplot(aes(x=period, y=median, group=source)) +
      geom_line(aes(color=source)) +
      geom_ribbon(aes(ymin=lower, ymax=upper, fill=source), alpha = 0.3) +
      facet_wrap(~area_name)

```
