---
title: "Interaction hyperparamters | 2020_05_27"
output: html_document
---

<style type="text/css">
.main-container {
  max-width: 1500px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, results="hide", echo=FALSE}
library(TMB)
library(INLA)
library(tidyverse)
library(abind)
library(sf)
library(spdep)
library(Matrix)
library(countrycode)
library(haven)
library(survival)
library(parallel)
library(demogsurv)
devtools::load_all("~/Documents/GitHub/naomi")
# library(naomi)
library(here)

naomi_data_path <- "~/Imperial College London/HIV Inference Group - Documents/Analytical datasets/naomi-data"
# naomi_data_path <- "~/naomi-data"

source(here("R/inputs.R"))
source(here("R/fertility_funs.R"))

iso3_current <-  "ZWE"
list2env(make_areas_population(iso3_current, naomi_data_path, full = FALSE), globalenv())

exclude_districts=""

asfr <- get_asfr_pred_df(iso3_current, area_level = 0, areas_long, project = FALSE)
mics_asfr <- NULL

mf <- make_model_frames(iso3_current, population, asfr, mics_asfr, exclude_districts, project=FALSE)

Z_age <- sparse.model.matrix(~0 + age_group, mf$mf_model)
Z_period <- sparse.model.matrix(~0 + period, mf$mf_model)

M_obs <- sparse.model.matrix(~0 + idx, mf$dist$obs)
Z_tips <- sparse.model.matrix(~0 + tips_f, mf$dist$obs)
X_tips_dummy <- model.matrix(~0 + tips_dummy, mf$dist$obs)

R_age <- make_rw_structure_matrix(ncol(Z_age), 1, TRUE)
R_period <- make_rw_structure_matrix(ncol(Z_period), 2, TRUE)
R_tips <- make_rw_structure_matrix(ncol(Z_tips), 1, TRUE)

compile(here("tmb/fertility_tmb_dev.cpp"))               # Compile the C++ file
dyn.load(dynlib(here("tmb/fertility_tmb_dev")))

tmb_int <- list()

tmb_int$data <- list(M_obs = M_obs,
             Z_age = Z_age,
             Z_period = Z_period,
             Z_interaction1 = sparse.model.matrix(~0 + id.interaction1, mf$mf_model),
             R_age = R_age,
             R_period = R_period,
             births_obs = mf$dist$obs$births,
             log_offset = log(mf$dist$obs$pys),
             mics_toggle = mf$mics_toggle,
             out_toggle = mf$out_toggle
)

tmb_int$par <- list(
  beta_0 = 0,
  
  u_age = rep(0, ncol(Z_age)),
  log_sigma_rw_age = log(2.5),
  
  u_period = rep(0, ncol(Z_period)),
  log_sigma_rw_period = log(2.5),
  
  eta1 = array(0, c(ncol(Z_period), ncol(Z_age))),
  log_sigma_eta1 = log(2.5),
  lag_logit_eta1_phi_age = 0,
  lag_logit_eta1_phi_period = 0
)

tmb_int$random <- c("beta_0", "u_age", "u_period", "eta1")

obj <-  MakeADFun(data = tmb_int$data,
                  parameters = tmb_int$par,
                  DLL = "fertility_tmb_dev",
                  random = tmb_int$random,
                  hessian = FALSE)

f <- nlminb(obj$par, obj$fn, obj$gr)
f$par.fixed <- f$par
f$par.full <- obj$env$last.par

fit <- c(f, obj = list(obj))
fit$sdreport <- sdreport(fit$obj, fit$par)

class(fit) <- "naomi_fit"  # this is hacky...
fit <- sample_tmb(fit, random_only = FALSE)
```

``` {r message=FALSE, warning=FALSE, results="hide", echo=FALSE}

zwe.m <- inla(
              births ~ f(id.age_group, model="rw1") + f(id.period, model="rw2") + f(id.age_group2, model = "ar1", group = id.period, control.group = list(model = "ar1")),
              family="xpoisson", data=asfr, E=pys,
              control.family=list(link='log'),
              control.predictor=list(compute=TRUE, link=1),
              control.inla = list(strategy = "gaussian", int.strategy = "eb"),
              control.compute=list(config = TRUE, dic= FALSE, cpo=FALSE),
              verbose=TRUE)

inla_log_prec_rw_age <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.age_group`)

inla_log_prec_rw_period <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.period`)

inla_log_prec_eta1 <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.age_group2`)
inla_eta1_phi_age <- data.frame(2*exp(zwe.m$internal.marginals.hyperpar$`Rho_intern for id.age_group2`)/(1+exp(zwe.m$internal.marginals.hyperpar$`Rho_intern for id.age_group2`))-1)
inla_eta1_phi_period <- data.frame(2*exp(zwe.m$internal.marginals.hyperpar$`Group rho_intern for id.age_group2`)/(1+exp(zwe.m$internal.marginals.hyperpar$`Group rho_intern for id.age_group2`))-1)


p1 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_age, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_age, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_age, aes(y=y))+
  labs(title = "log_prec_rw_age")

p2 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_period, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_period, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_period, aes(y=y))+
  labs(title = "log_prec_rw_period")

p4 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_tips, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_eta1, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_eta1, aes(y=y))+
  labs(title = "log_prec_eta1")

p5 <- 
  # data.frame("x" = 1/(1+exp(-stan_samples$lag_logit_eta1_phi_age)), "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$eta1_phi_age, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_eta1_phi_age, aes(y=y))+
  labs(title = "eta1_phi_age")

p6 <- 
  # data.frame("x" = 1/(1+exp(-stan_samples$lag_logit_eta1_phi_period)), "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$eta1_phi_period, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_eta1_phi_period, aes(y=y))+
  labs(title = "eta1_phi_period")
```

``` {r}

gridExtra::grid.arrange(p1, p2, p4, p5, p6, ncol=3)

```

## Add tips

``` {r message=FALSE, warning=FALSE, results="hide", echo=FALSE}

tmb_int$data <- c(tmb_int$data, 
                  "X_tips_dummy" = list(X_tips_dummy),
                  "R_tips" = R_tips,
                  "Z_tips" = Z_tips)

tmb_int$par <- c(tmb_int$par, 
                 "beta_tips_dummy" = rep(0, ncol(X_tips_dummy)),
                 "u_tips" = list(rep(0, ncol(Z_tips))),
                 "log_sigma_rw_tips" = log(2.5)
)

tmb_int$random <- c(tmb_int$random, "beta_tips_dummy", "u_tips")

compile(here("tmb/eta1_tips_admin0.cpp"))               # Compile the C++ file
dyn.load(dynlib(here("tmb/eta1_tips_admin0")))

obj <-  MakeADFun(data = tmb_int$data,
                  parameters = tmb_int$par,
                  DLL = "eta1_tips_admin0",
                  random = tmb_int$random,
                  hessian = FALSE)

f <- nlminb(obj$par, obj$fn, obj$gr)
f$par.fixed <- f$par
f$par.full <- obj$env$last.par

fit <- c(f, obj = list(obj))
fit$sdreport <- sdreport(fit$obj, fit$par)

class(fit) <- "naomi_fit"  # this is hacky...
fit <- sample_tmb(fit, random_only = FALSE)

```

``` {r message=FALSE, warning=FALSE, results="hide", echo=FALSE}

zwe.m <- inla(
              births ~ f(id.age_group, model="rw1") + f(id.period, model="rw2") + f(id.age_group2, model = "ar1", group = id.period, control.group = list(model = "ar1")) + f(id.tips, model="rw1"),
              family="xpoisson", data=asfr, E=pys,
              control.family=list(link='log'),
              control.predictor=list(compute=TRUE, link=1),
              control.inla = list(strategy = "gaussian", int.strategy = "eb"),
              control.compute=list(config = TRUE, dic= FALSE, cpo=FALSE),
              verbose=TRUE)

inla_log_prec_rw_age <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.age_group`)
inla_log_prec_rw_period <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.period`)
inla_log_prec_rw_tips <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.tips`)

inla_log_prec_eta1 <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.age_group2`)
inla_eta1_phi_age <- data.frame(2*exp(zwe.m$internal.marginals.hyperpar$`Rho_intern for id.age_group2`)/(1+exp(zwe.m$internal.marginals.hyperpar$`Rho_intern for id.age_group2`))-1)
inla_eta1_phi_period <- data.frame(2*exp(zwe.m$internal.marginals.hyperpar$`Group rho_intern for id.age_group2`)/(1+exp(zwe.m$internal.marginals.hyperpar$`Group rho_intern for id.age_group2`))-1)


p1 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_age, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_age, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_age, aes(y=y))+
  labs(title = "log_prec_rw_age")

p2 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_period, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_period, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_period, aes(y=y))+
  labs(title = "log_prec_rw_period")

p3 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_tips, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_tips, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_tips, aes(y=y))+
  labs(title = "log_prec_rw_tips")

p4 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_tips, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_eta1, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_eta1, aes(y=y))+
  labs(title = "log_prec_eta1")

p5 <- 
  # data.frame("x" = 1/(1+exp(-stan_samples$lag_logit_eta1_phi_age)), "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$eta1_phi_age, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_eta1_phi_age, aes(y=y))+
  labs(title = "eta1_phi_age")

p6 <- 
  # data.frame("x" = 1/(1+exp(-stan_samples$lag_logit_eta1_phi_period)), "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$eta1_phi_period, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_eta1_phi_period, aes(y=y))+
  labs(title = "eta1_phi_period")
```

``` {r}

gridExtra::grid.arrange(p1, p2, p3, p4, p5, p6, ncol=3)

```

``` {r message=FALSE, warning=FALSE, results="hide", echo=FALSE}

compile(here("tmb/eta1_ar1_admin0.cpp"))               # Compile the C++ file
dyn.load(dynlib(here("tmb/eta1_ar1_admin0")))

tmb_int <- list()

tmb_int$data <- list(M_obs = M_obs,
             Z_age = Z_age,
             Z_period = Z_period,
             Z_interaction1 = sparse.model.matrix(~0 + id.interaction1, mf$mf_model),
             R_age = R_age,
             R_period = R_period,
             births_obs = mf$dist$obs$births,
             log_offset = log(mf$dist$obs$pys),
             mics_toggle = mf$mics_toggle,
             out_toggle = mf$out_toggle
)

tmb_int$par <- list(
  beta_0 = 0,
  
  u_age = rep(0, ncol(Z_age)),
  log_sigma_rw_age = log(2.5),
  
  u_period = rep(0, ncol(Z_period)),
  log_sigma_rw_period = log(2.5),
  
  eta1 = array(0, c(ncol(Z_period), ncol(Z_age))),
  log_sigma_eta1 = log(2.5),
  lag_logit_eta1_phi_age = 0,
  lag_logit_eta1_phi_period = 0
)

tmb_int$random <- c("beta_0", "u_age", "u_period", "eta1")

obj <-  MakeADFun(data = tmb_int$data,
                  parameters = tmb_int$par,
                  DLL = "eta1_ar1_admin0",
                  random = tmb_int$random,
                  hessian = FALSE)

f <- nlminb(obj$par, obj$fn, obj$gr)
f$par.fixed <- f$par
f$par.full <- obj$env$last.par

fit <- c(f, obj = list(obj))
fit$sdreport <- sdreport(fit$obj, fit$par)

class(fit) <- "naomi_fit"  # this is hacky...
fit <- sample_tmb(fit, random_only = FALSE)

```

## Add space (admin-1 for ease)

``` {r include = FALSE}

make_model_frames_admin1 <- function(iso3_current, population, asfr, mics_asfr = NULL, exclude_districts = "", project = FALSE) {
  
  population <- area_populations(population, areas_wide) %>%
    filter(sex == "female") %>%
    ungroup %>%
    select(-sex)
  
  population <- crossing(area_id = unique(population$area_id),
           age_group = unique(population$age_group),
           period = 1995:2020
  ) %>%
    left_join(population) %>%
    group_by(area_id, age_group) %>%
    mutate(population = exp(zoo::na.approx(log(population), period, na.rm = FALSE))) %>%
    fill(population, .direction="up")
    
  
  # population <- crossing(area_id = unique(population$area_id),
  #          age_group = unique(population$age_group),
  #          period = 1995:(min(population$period)-1)
  # ) %>%
  #   left_join(population %>% filter(period == min(period)) %>% select(-period)) %>%
  #   bind_rows(population)
   
  if(!project) {
  
  if(!is.null(mics_asfr)) {
    df <- asfr %>%
      bind_rows(mics_asfr)
  } else {
    df <- asfr
    
  }
  
  max_year <- max(df$period)
    
  } else {
    
    max_year <- project
  }
  
  area_merged <- st_read(file.path(naomi_data_path, iso3_current, "data", paste0(tolower(iso3_current), "_areas.geojson")))
  areas <- create_areas(area_merged = area_merged)
  area_aggregation <- create_area_aggregation(area_merged$area_id[area_merged$naomi_level], areas) %>%
    filter(!model_area_id %in% exclude_districts)
  
  ## Make model frame.
  mf_model <- crossing(period = 1995:max_year,
                 age_group = c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49"),
                 # area_id = unique(area_aggregation$model_area_id)) %>%
                 area_id = filter(areas_long, iso3 == iso3_current, area_level == 1)$area_id) %>%
                 # area_id = iso3_current) %>%
    left_join(population %>%
                select(area_id, period, age_group, population)
    ) %>%
    # mutate(area_id = factor(area_id, levels = unique(area_aggregation$model_area_id)),
    mutate(area_id = factor(area_id, levels = filter(areas_long, iso3 == iso3_current, area_level == 1)$area_id),
    # mutate(area_id = factor(iso3_current),
           age_group = factor(age_group, levels = c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49")),
           period = factor(period)
           # restype = ifelse(area_id %in% c(
           #  filter(areas_long, parent_area_id == "ETH_1_10")$area_id,
           #  filter(areas_long, str_detect(area_name, "Town"))$area_id,
           #  filter(areas_long, area_name %in% c("Harari", "Fafen (Jijiga)"))$area_id),
           #  1, 0)
    ) %>%
    arrange(period, area_id, age_group) %>%
    mutate(idx = factor(row_number()),
           id.interaction_3d = factor(group_indices(., age_group, period, area_id)),
           # id.interaction_age_time = factor(group_indices(., age_group, period)),
           id.interaction1 = factor(group_indices(., age_group, period)),
           id.interaction2 = factor(group_indices(., period, area_id)),
           id.interaction3 = factor(group_indices(., age_group, area_id))
    ) %>%
   droplevels()
  
  obs <- asfr %>%
    mutate(period = factor(period, levels(mf_model$period))) %>%
    filter(!is.na(surveyid), !area_id %in% exclude_districts) %>%
    select(area_id, period, age_group, tips, births, pys) %>%
    left_join(mf_model) %>%
    mutate(tips_dummy = as.integer(tips > 5),
           tips_f = factor(tips),
           #####
           # urban_dummy = ifelse(area_id %in% c(
           #   filter(areas_long, parent_area_id == "ETH_1_10")$area_id,
           #   filter(areas_long, str_detect(area_name, "Town"))$area_id,
           #   filter(areas_long, area_name %in% c("Harari", "Fafen (Jijiga)"))$area_id),
           # 1, 0),
           #####
           age_group = factor(age_group, levels(mf_model$age_group)),
           area_id = factor(area_id, levels(mf_model$area_id)),
           period = factor(period, levels(mf_model$period)),
    )
  
  mf <- list()
  mf$mf_model <- mf_model
  mf$dist$obs <- obs
  mf$mics_toggle <- 0
  mf$out_toggle <- 0
  
  ## Outputs

  if(unique(asfr %>%left_join(areas_long) %>% .$naomi_level)) {  
    
    mf_out <- crossing(
      area_id = area_aggregation$area_id,
      age_group = unique(mf_model$age_group),
      period = unique(mf_model$period)
    ) %>%
      arrange(area_id, age_group, period) %>%
      mutate(out_idx = row_number()) %>%
      droplevels()
  
    join_out <- crossing(area_aggregation,
                         age_group = unique(mf_model$age_group),
                         period = unique(mf_model$period)) %>%
      full_join(mf_model %>%
                  select(area_id, age_group, period, idx), by = c("model_area_id" = "area_id",
                                                                  "age_group",
                                                                  "period")
      ) %>%
      full_join(mf_out) %>%
      # full_join(mf_out, by=c("area_id",
      #                        "period",
      #                        "age_group_out" = "age_group")
      #           ) %>%
      mutate(x=1) %>%
      filter(!is.na(model_area_id))
    
    A_out <- spMatrix(nrow(mf_out), nrow(mf_model), join_out$out_idx, as.integer(join_out$idx), join_out$x)
    
    # mf_out_restype <- crossing(
    #   age_group = unique(mf_model$age_group),
    #   period = unique(mf_model$period),
    #   restype = c(1, 0)
    #   ) %>%
    # arrange(age_group, period) %>%
    # mutate(out_idx = row_number()) %>%
    # droplevels()
    # 
    # join_out_restype <- crossing(
    #   age_group = unique(mf_model$age_group),
    #   period = unique(mf_model$period),
    #   restype = c(1, 0)
    # ) %>%
    # full_join(mf_model %>%
    #             select(age_group, period, restype, idx)) %>%
    # full_join(mf_out_restype) %>%
    # # full_join(mf_out, by=c("area_id",
    # #                        "period",
    # #                        "age_group_out" = "age_group")
    # #           ) %>%
    # mutate(x=1)
    # 
    # A_out_restype <- spMatrix(nrow(mf_out_restype), nrow(mf_model), join_out_restype$out_idx, as.integer(join_out_restype$idx), join_out_restype$x)
    # 
    # mf$out$mf_out_restype <- mf_out_restype
    # mf$out$A_out_restype <- A_out_restype
    
    mf$out$mf_out <- mf_out
    mf$out$A_out <- A_out
    mf$out_toggle <- 1
  
  }
  
  if(!is.null(mics_asfr)) {
    
    
    
    mf_mics <- crossing(area_id = unique(mics_asfr$area_id),
                       period = unique(mf_model$period),
                       age_group = unique(mf_model$age_group)
    ) %>%
      filter(!area_id %in% unique(filter(areas_wide, area_id %in% exclude_districts)$area_id1)) %>%
      mutate(idx = factor(row_number()))
    
    join_mics <- mf_mics %>%
      rename(idx_row = idx) %>%
      left_join(area_aggregation) %>%
      left_join(mf_model, by=c("age_group", "period", "model_area_id" = "area_id")) %>%
      mutate(idx_col = row_number(),
             x=1) %>%
      type.convert()
    
    A_mics <- sparseMatrix(i = join_mics$idx_row, j=join_mics$idx_col, x=join_mics$x, use.last.ij = TRUE)
    
    
    obs_mics <- mics_asfr %>%
      filter(!area_id %in% unique(filter(areas_wide, area_id %in% exclude_districts)$area_id1)) %>%
      mutate(period = factor(period, levels(mf_model$period))) %>%
      left_join(mf_mics) %>%
      select(area_id, period, age_group, tips, births, pys, idx) %>%
      mutate(tips_dummy = as.integer(tips > 2),
             tips_f = factor(tips, levels(obs$tips_f)),
             age_group = factor(age_group, levels(mf_model$age_group)),
             idx =factor(idx, levels(mf_mics$idx))
      )
    
    mf$mics$obs <- obs_mics
    mf$mics$A_mics <- A_mics
    mf$mics_toggle <- 1
    
  }
  
  return(mf)
}
```

``` {r message=FALSE, warning=FALSE, results="hide", echo=FALSE}
asfr <- get_asfr_pred_df(iso3_current, area_level = 1, areas_long, project = FALSE)
mf <- make_model_frames_admin1(iso3_current, population, asfr, mics_asfr, exclude_districts, project=FALSE)

Z_spatial <- sparse.model.matrix(~0 + area_id, mf$mf_model)
Z_age <- sparse.model.matrix(~0 + age_group, mf$mf_model)
Z_period <- sparse.model.matrix(~0 + period, mf$mf_model)

M_obs <- sparse.model.matrix(~0 + idx, mf$dist$obs) 
Z_tips <- sparse.model.matrix(~0 + tips_f, mf$dist$obs)
X_tips_dummy <- model.matrix(~0 + tips_dummy, mf$dist$obs)

R_spatial <- make_adjacency_matrix(iso3_current, areas_long, boundaries, exclude_districts, level= 1)
R_tips <- make_rw_structure_matrix(ncol(Z_tips), 1, TRUE)
R_age <- make_rw_structure_matrix(ncol(Z_age), 1, TRUE)
R_period <- make_rw_structure_matrix(ncol(Z_period), 2, TRUE)

compile(here("tmb/eta1_tips_admin1.cpp"))               # Compile the C++ file
dyn.load(dynlib(here("tmb/eta1_tips_admin1")))

tmb_int <- list()

tmb_int$data <- list(M_obs = M_obs,
             X_tips_dummy = X_tips_dummy,
             Z_tips = Z_tips,
             Z_age = Z_age,
             Z_period = Z_period,
             Z_spatial = Z_spatial,
             Z_interaction1 = sparse.model.matrix(~0 + id.interaction1, mf$mf_model),
             R_tips = R_tips,
             R_age = R_age,
             R_period = R_period,
             R_spatial = R_spatial,
             log_offset = log(mf$dist$obs$pys),
             births_obs = mf$dist$obs$births,
             mics_toggle = mf$mics_toggle,
             out_toggle = mf$out_toggle
)

tmb_int$par <- list(
  beta_0 = 0,
  
  beta_tips_dummy = rep(0, ncol(X_tips_dummy)),
  u_tips = rep(0, ncol(Z_tips)),
  log_sigma_rw_tips = log(2.5),
  
  u_age = rep(0, ncol(Z_age)),
  log_sigma_rw_age = log(2.5),
  
  u_period = rep(0, ncol(Z_period)),
  log_sigma_rw_period = log(2.5),
  
  u_spatial_str = rep(0, ncol(Z_spatial)),
  u_spatial_iid = rep(0, ncol(Z_spatial)),
  log_sigma_spatial = log(2.5),
  logit_spatial_rho = 0,
  
  eta1 = array(0, c(ncol(Z_period), ncol(Z_age))),
  log_sigma_eta1 = log(2.5),
  lag_logit_eta1_phi_age = 0,
  lag_logit_eta1_phi_period = 0
)

tmb_int$random <- c("beta_0",  "beta_tips_dummy","u_tips", "u_age", "u_period", "eta1", "u_spatial_str", "u_spatial_iid")

obj <-  MakeADFun(data = tmb_int$data,
                  parameters = tmb_int$par,
                  DLL = "eta1_tips_admin1",
                  #  random = c("beta_mf", "beta_tips_dummy", "u_tips", "u_age", "u_period", "u_spatial_str", "u_spatial_iid", "eta1", "eta2", "eta3"),
                  random = tmb_int$random,
                  hessian = FALSE)

f <- nlminb(obj$par, obj$fn, obj$gr)
f$par.fixed <- f$par
f$par.full <- obj$env$last.par

fit <- c(f, obj = list(obj))
fit$sdreport <- sdreport(fit$obj, fit$par)

class(fit) <- "naomi_fit"  # this is hacky...
fit <- sample_tmb(fit, random_only=TRUE)
```

``` {r message=FALSE, warning=FALSE, results="hide", echo=FALSE}

zwe.m <- readRDS(here("countries/ZWE/mods/ZWE_INLA_admin1_eta1.rds"))


inla_log_prec_rw_age <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.age_group`)
inla_log_prec_rw_period <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.period`)
inla_log_prec_rw_tips <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.tips`)

inla_logit_rho <- data.frame(zwe.m$internal.marginals.hyperpar$`Logit phi for id.district`)
inla_log_prec_spatial <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.district`)

inla_log_prec_eta1 <- data.frame(zwe.m$internal.marginals.hyperpar$`Log precision for id.age_group2`)
inla_eta1_phi_age <- data.frame(2*exp(zwe.m$internal.marginals.hyperpar$`Rho_intern for id.age_group2`)/(1+exp(zwe.m$internal.marginals.hyperpar$`Rho_intern for id.age_group2`))-1)
inla_eta1_phi_period <- data.frame(2*exp(zwe.m$internal.marginals.hyperpar$`Group rho_intern for id.age_group2`)/(1+exp(zwe.m$internal.marginals.hyperpar$`Group rho_intern for id.age_group2`))-1)

p1 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_age, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_age, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_age, aes(y=y))+
  labs(title = "log_prec_rw_age")

p2 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_period, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_period, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_period, aes(y=y))+
  labs(title = "log_prec_rw_period")

p3 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_tips, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_rw_tips, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_rw_tips, aes(y=y))+
  labs(title = "log_prec_rw_tips")

p4 <- 
  # data.frame("x" = -2*stan_samples$log_sigma_rw_tips, "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$log_tau2_eta1, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_eta1, aes(y=y))+
  labs(title = "log_prec_eta1")

p5 <- 
  # data.frame("x" = 1/(1+exp(-stan_samples$lag_logit_eta1_phi_age)), "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$eta1_phi_age, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_eta1_phi_age, aes(y=y))+
  labs(title = "eta1_phi_age")

p6 <- 
  # data.frame("x" = 1/(1+exp(-stan_samples$lag_logit_eta1_phi_period)), "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$eta1_phi_period, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_eta1_phi_period, aes(y=y))+
  labs(title = "eta1_phi_period")

p7 <- 
  bind_rows(data.frame("x" = fit$sample$log_tau2_spatial, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_log_prec_spatial, aes(y=y))+
  labs(title = "log_prec_spatial")

p8 <- 
  # data.frame("x" = 1/(1+exp(-stan_samples$lag_logit_eta1_phi_period)), "source" = "tmbstan") %>%
  bind_rows(data.frame("x" = fit$sample$logit_spatial_rho, "source" = "tmb")) %>%
  ggplot(aes(x=x)) +
  geom_density(aes(group=source, fill=source), alpha=0.7) +
  geom_point(data=inla_logit_rho, aes(y=y))+
  labs(title = "logit_spatial_rho")

```

``` {r}

gridExtra::grid.arrange(p1, p2, p3, p4, p5, p6, p7, p8, ncol=3)

```